version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: backend:latest
    container_name: backend-container
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - FRONTEND_URL=${FRONTEND_URL}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - egrade-network

  db:
    image: postgres:16
    container_name: postgres-container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - egrade-network

  frontend:
    build:
      context: ./frontend
    image: frontend:latest
    container_name: frontend-container
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
    ports:
      - '3000:80'
    networks:
      - egrade-network


networks:
  egrade-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
